apiVersion: v1
kind: Secret
metadata:
  name: ragflow-knowledge-portal-secret
  labels:
    app.kubernetes.io/component: ragflow-knowledge-portal
    app.kubernetes.io/instance: ragflow-knowledge-portal
    app.kubernetes.io/name: ragflow-knowledge-portal
    env_instance: "${ENV_INSTANCE}"
    project: "${PROJECT_NAME}"
    service: ragflow-knowledge-portal
type: Opaque
stringData:
  RAGFLOW_API_KEY: "${RAGFLOW_API_KEY}"
  LLM_API_KEY: "${LLM_API_KEY}"
