apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-knowledge-portal-config
  labels:
    app.kubernetes.io/component: ragflow-knowledge-portal
    app.kubernetes.io/instance: ragflow-knowledge-portal
    app.kubernetes.io/name: ragflow-knowledge-portal
    env_instance: "${ENV_INSTANCE}"
    project: "${PROJECT_NAME}"
    service: ragflow-knowledge-portal
data:
  RAGFLOW_BASE_URL: "${RAGFLOW_BASE_URL}"
  RAGFLOW_TIMEOUT: "${RAGFLOW_TIMEOUT}"
  LLM_BASE_URL: "${LLM_BASE_URL}"
  LLM_MODEL: "${LLM_MODEL}"
  LLM_TIMEOUT: "${LLM_TIMEOUT}"
  SERVICE_HOST: "0.0.0.0"
  SERVICE_PORT: "${SERVICE_PORT}"
